# Generated by Django 5.2.3 on 2025-06-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days_active', models.JSONField(help_text="Days this config is active, e.g. ['Mon', 'Tue']")),
                ('base_distance', models.FloatField(help_text='Base distance in KMs')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for base distance', max_digits=10)),
                ('additional_price_per_km', models.DecimalField(decimal_places=2, help_text='Price per KM after base distance', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
