# Generated by Django 5.2.3 on 2025-06-16 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_minutes', models.PositiveIntegerField()),
                ('max_minutes', models.PositiveIntegerField()),
                ('multiplier', models.FloatField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_multipliers', to='pricing.pricingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='WaitingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_minutes', models.PositiveIntegerField()),
                ('charge_per_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_charges', to='pricing.pricingconfig')),
            ],
        ),
    ]
