# Generated by Django 5.2.3 on 2025-06-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_configchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='days_active',
            field=models.CharField(max_length=100),
        ),
    ]
