# Generated by Django 5.2.3 on 2025-06-16 03:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_pricingconfig_days_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='additional_price_per_km',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='base_distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='base_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='days_active',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), size=None),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
