# Generated by Django 5.2.3 on 2025-06-16 05:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_pricingconfig_additional_price_per_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='days_active',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
